# This workflow is used to convert changed EL.data.model.csv to EL.data.model.jsonld
# and push the updated ELITE.data.model.jsonld to feature branch

name: CI
permissions: write-all

on:
  pull_request:
    branches: main
    paths: 'EL.data.model.csv'
  workflow_dispatch:
jobs:
  CI:
    name: schema-convert
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.9'

      - name: Install Schematic
        shell: bash
        run: |
          pip3 install poetry
          git clone --single-branch --branch main https://github.com/Sage-Bionetworks/schematic.git
          cd schematic
          poetry build
          pip3 install dist/schematicpy-*-py3-none-any.whl
          
      - name: Convert .csv to .jsonld
        shell: bash
        run: |
          schematic schema convert EL.data.model.csv

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit the changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add EL.data.model.jsonld
          git commit -m "GitHub Action: convert *.model.csv to *.model.jsonld" || echo "No changes to commit"

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

